name: bayes_spec-dev
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyter
  - ipykernel
  - ipywidgets
  - versioneer
  - black
  - flake8
  - pytest
  - pytest-cov
  - numpy
  - pymc==5.28.5
  - pytensor
  - nutpie
  - numba
  - arviz
  - matplotlib
  - scipy
  - scikit-learn
  - graphviz
  - jaxlib==0.9.2
  - jax==0.9.2
  - blackjax
  - numpyro
  - pip
