name: bayes_spec-dev
channels:
  - conda-forge
  - nvidia
dependencies:
  - ipython
  - jupyter
  - ipykernel
  - ipywidgets
  - versioneer
  - black
  - flake8
  - pytest
  - pytest-cov
  - pymc<6
  - pytensor
  - nutpie
  - numba
  - arviz<1.0
  - matplotlib
  - scipy
  - scikit-learn
  - graphviz
  - nvidia::cuda-toolkit
  - jaxlib[cuda]
  - jax
  - blackjax<1.3
  - numpyro
  - pip
