name: bayes_spec-dev
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyter
  - ipykernel
  - ipywidgets
  - versioneer
  - black
  - flake8
  - pytest
  - pytest-cov
  - numpy
  - pymc<6
  - pytensor
  - nutpie
  - numba
  - arviz
  - matplotlib
  - scipy
  - scikit-learn
  - graphviz
  - jaxlib
  - jax
  - blackjax<1.3
  - numpyro
  - pip
